site_name: Divine Heart Beats
site_description: Christian Music Band - Singing for the Glory of God
site_author: Divine Heart Beats

theme:
  name: mkdocs

markdown_extensions:
  - tables
  - fenced_code
